version: '3'

services:
  db:
    container_name: Techchallenge
    image: postgres:9.4
    restart: always
    volumes:
     - ./data:/var/lib/postgresql/data
     - ./scripts/createbanco.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dbEnergia
    ports:
      - 5432:5432
